/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ImageBoundingBoxRenderer: typeof import('./src/components/app/ImageBoundingBoxRenderer.vue')['default']
    MortalityCreateForm: typeof import('./src/components/app/dashboard/MortalityCreateForm.vue')['default']
    ReadingBarChart: typeof import('./src/components/app/analytics/ReadingBarChart.vue')['default']
    ReadingLineChart: typeof import('./src/components/app/analytics/ReadingLineChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserForgotPasswordForm: typeof import('./src/components/auth/UserForgotPasswordForm.vue')['default']
    UserSignInForm: typeof import('./src/components/auth/UserSignInForm.vue')['default']
    UserSignUpForm: typeof import('./src/components/auth/UserSignUpForm.vue')['default']
  }
}
