/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActuatorCard: typeof import('./src/components/app/config/ActuatorCard.vue')['default']
    ActuatorCreateForm: typeof import('./src/components/app/config/ActuatorCreateForm.vue')['default']
    ActuatorUpdateForm: typeof import('./src/components/app/config/ActuatorUpdateForm.vue')['default']
    ConditionCard: typeof import('./src/components/app/config/ConditionCard.vue')['default']
    ConditionCreateForm: typeof import('./src/components/app/config/ConditionCreateForm.vue')['default']
    ConditionForm: typeof import('./src/components/app/config/ConditionForm.vue')['default']
    ConditionUpdateForm: typeof import('./src/components/app/config/ConditionUpdateForm.vue')['default']
    ImageBoundingBoxRenderer: typeof import('./src/components/app/dashboard/detection/ImageBoundingBoxRenderer.vue')['default']
    MortalityCreateForm: typeof import('./src/components/app/dashboard/MortalityCreateForm.vue')['default']
    ReadingBarChart: typeof import('./src/components/app/analytics/ReadingBarChart.vue')['default']
    ReadingLineChart: typeof import('./src/components/app/analytics/ReadingLineChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SensorCard: typeof import('./src/components/app/config/SensorCard.vue')['default']
    SensorCreateForm: typeof import('./src/components/app/config/SensorCreateForm.vue')['default']
    SensorUpdateForm: typeof import('./src/components/app/config/SensorUpdateForm.vue')['default']
    ThresholdCard: typeof import('./src/components/app/config/ThresholdCard.vue')['default']
    ThresholdCreateForm: typeof import('./src/components/app/config/ThresholdCreateForm.vue')['default']
    ThresholdForm: typeof import('./src/components/app/config/ThresholdForm.vue')['default']
    ThresholdUpdateForm: typeof import('./src/components/app/config/ThresholdUpdateForm.vue')['default']
    ToastQueue: typeof import('./src/components/ToastQueue.vue')['default']
    UserForgotPasswordForm: typeof import('./src/components/auth/UserForgotPasswordForm.vue')['default']
    UserResetPasswordForm: typeof import('./src/components/auth/UserResetPasswordForm.vue')['default']
    UserSignInForm: typeof import('./src/components/auth/UserSignInForm.vue')['default']
    UserSignUpForm: typeof import('./src/components/auth/UserSignUpForm.vue')['default']
  }
}
